### ISSUE TITLE
TestFlight/IOS App

### ISSUE THREAD

**Issue by Shooter0423** [ammolytics/projects#32]
Sorry for being dense, but I am not figuring out how to test the IOS App. I have TestFlight installed on my from, but where do I (or how do I) get an invitation code.
Thanks

**Comment by erichiggins** [comment]
No problem, I linked to it from #14 but here ya go!
https://testflight.apple.com/join/1XSoUPL3

**Comment by Shooter0423** [comment]
Thanks, that worked. For some reason using the link inside the email did the trick. Like the IOS keypad better, unit didn’t seem to display correctly on my screen, just saw a “g” assuming it should 2 characters.
