### ISSUE TITLE
Write OpenTrickler FAQ

### ISSUE THREAD

**Issue by erichiggins** [ammolytics/projects#42]
Many of the questions for the OpenTrickler could be answered in an FAQ.

Common items:

- Not showing up on BT (bad adapter, scale not connected/detected)
- Support for other scales
- Accessing the CODE partition
- Will do you make it for Arduino/ESP/etc
- Powder drop support
- Accessing the log web page  #41

**Comment by ande7824** [comment]
This may help someone, but I figured out how to access the CODE partition in Windows 10 by utilizing the Windows disk utility with the SD card in my computer.  The CODE partition shows up in the card but didn't have a drive letter assigned so I right clicked and assigned a letter and it showed up right away.

**Comment by erichiggins** [comment]
Added here:
https://github.com/ammolytics/projects/blob/develop/trickler/README.md#frequently-asked-questions
